# Generated by Django 2.1 on 2018-09-13 22:34

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to=blog.models.post_upload_path),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='temp', max_length=140, unique=True),
        ),
    ]
