# Generated by Django 2.1 on 2018-09-13 22:34

from django.db import migrations, models
import portfolio.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('title', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('image', models.ImageField(blank=True, upload_to=portfolio.models.project_upload_path)),
                ('short', models.CharField(max_length=1000)),
                ('long', models.TextField(max_length=10000)),
                ('live_url', models.URLField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(default='auto', max_length=100, unique=True)),
            ],
        ),
    ]
