# Generated by Django 2.1 on 2018-09-14 04:43

from django.db import migrations, models
import portfolio.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to=portfolio.models.project_upload_path),
        ),
    ]
